news/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.news_today, name='news_today'),
    re_path(r'archives/(\d{4}-\d{2}-\d{2})/',
            views.past_days_news, name='past_news'),
    path('search/', views.search_results, name='search_results'),
    path('all-news/', views.all_news, name='all_news'),
    path('article/<int:article_id>', views.article, name='article')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tribune/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("news.urls")),
]

news/models.py
import datetime
from django.db import models


class Editor(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(null=True)
    # Making the phone_number optional
    phone_number = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['-first_name']


class tags(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'tags'


class Article(models.Model):
    title = models.CharField(max_length=60)
    post = models.TextField()
    editor = models.ForeignKey(Editor, on_delete=models.CASCADE)
    tags = models.ManyToManyField(tags)
    pub_date = models.DateField(auto_now_add=True)
    image = models.ImageField(
        upload_to='articles/', blank=True, null=True)

    def __str__(self):
        return self.title

    @classmethod
    def todays_news(cls):
        today = datetime.date.today()
        news = cls.objects.filter(pub_date=today)
        return news

    @classmethod
    def search_by_title(cls, search_term):
        search_result = cls.objects.filter(title__icontains=search_term)
        return search_result


class NewsLetterRecipients(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)

news/forms.py
from django import forms


class NewsLetterForm(forms.Form):
    your_name = forms.CharField(label='First Name', max_length=30)
    email = forms.EmailField(label='Email')

news/views.py
import datetime
from django.db.models import Q
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import NewsLetterForm


def news_today(request):
    date = datetime.date.today()
    news = Article.todays_news()

    if request.method == 'POST':
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['your_name']
            email = form.cleaned_data['email']
            recipient = NewsLetterRecipients(name=name, email=email)
            recipient.save()
            HttpResponseRedirect('news_today')
        else:
            form = NewsLetterForm()

    context = {
        'date': date,
        'news': news,
        'letter_form': form,
    }

    return render(request, 'news/index.html', context)


def all_news(request):
    return render(request, 'news/index.html', {
        'news': Article.objects.all(),
    })


def past_days_news(request, past_date):

    try:
        date = datetime.datetime.strptime(past_date, '%Y-%m-%d').date()

    except ValueError:
        # Raise 404 error when ValueError is thrown
        raise Http404()
        assert False

    if date == datetime.date.today():
        return redirect(news_today)

    return render(request, 'news/past-news.html', {
        'date': date,
    })


def search_results(request):
    if request.method == 'POST':
        pass

    if 'article' in request.GET and request.GET['article']:
        search_term = request.GET.get('article')
        searched_articles = Article.search_by_title(search_term)
        message = f'{search_term}'
        return render(request, 'news/search.html', {
            'message': message,
            'articles': searched_articles
        })


def article(request, article_id):
    article = get_object_or_404(Article, pk=article_id)

    return render(request, 'news/article.html', {
        'article': article
    })

news/templates/news/article.html
{% extends "news/layout.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      <img src="{{ article.image.url }}" alt="" class="img-responsive">
    </div>
    <div class="row">
      <h1 class="text-center">{{ article.title }}</h1>
    </div>
    <div class="row">
      <p>{{ article.post }}</p>
    </div>
    <div class="row">
      <em>
        <p>~ Posted {{ article.pub_date|timesince }} by <strong>{{ article.editor.first_name }}</strong></p>
      </em>
    </div>
  </div>
{% endblock content %}

news/templates/news/index.html
{% extends "news/layout.html" %}
{% load bootstrap4 %}
{% block content %}
  <div class="container">
    {{ block.super }}
    <!-- Looping through news -->
    {% for news_item in news %}
      <div class="card text-center my-5 rounded-0 bg-light">

        <!-- The news article -->
        <div class="card-header pb-0">
          <!-- {{ news_item.tags.all }} -->
          <p>tags</p>
        </div>
        <div class="card-body">
          <div class="row">
            
            <!-- The first part -->
            <div class="card-body col-md-6 text-left">
              <h5 class="card-title">{{ news_item.title }}</h5>

              <!-- The summary -->
              <div class="text-left">
                {% if news_item.summary %}
                  <p class="card-text">{{ article.summary }}</p>
                {% else %}
                  <p class="card-text">This
                    <a href="{% url 'news:article' news_item.id %}" >
                    <strong>'{{ news_item.title }}'</strong>
                    </a>  is a good read. </p>
                {% endif %}
                <a href="{% url 'news:article' news_item.id %}" class="btn btn-info rounded-0">Read</a>
              </div>
            </div>

            <!-- The image -->
            <div class="col-md-6">
              <div class="float-right">
                <img 
                  class="card-img-right float-right" 
                  src="{{ news_item.image.url }}" 
                  alt="Card image cap" 
                  style="width: 400px; height:auto;"
                >
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer text-muted">
          Posted {{ news_item.pub_date|timesince }} by {{ news_item.editor.first_name }}
        </div>
      </div>

      <!-- If empty -->
      {% empty %}
      <div class="row jumbotron">
        <h2 class="text-center">There are no news</h2>
      </div>
    {% endfor %}

    <!-- Looping trough news end -->
    <div class="container-fluid row">
      <form action="{% url 'news:news_today' %}" method="post" class="form col-md-6">
        {% csrf_token %}
        {% bootstrap_form letter_form layout='inline' class='rounded-0' %}
        <input type="submit" value="Subscribe" class="btn btn-outline-dark rounded-0">
      </form>
    </div>
  </div>
{% endblock content %}

news/templates/news/layout.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% if title %}
        Moringa Tribune - {{ title }}
      {% else %}
        Moringa Tribune
      {% endif %}
    </title>
    {% block styles %}
      {% bootstrap_css %}
      <link rel="stylesheet" href="{% static 'news/css/main.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Pangolin&display=swap" rel="stylesheet">
    {% endblock styles %}
  </head>
  <body style="font-family: 'Pangolin', cursive;">
    <!-- Navbar -->
    {% include "news/navbar.html" %}

    <div class="container">
      <!-- The body block -->
      {% block content %} 
        {% if date %}
          <h1 class="text-center">News for {{ date|date:"l d-F Y" }} </h1>
        {% endif %}
      {% endblock content %}
    </div>

    <!-- Scripts -->
    {% block scripts %}
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      {% bootstrap_javascript %}
    {% endblock scripts %}
  </body>
</html>

news/templates/news/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid px-5">
    <a class="navbar-brand" href="{% url 'news:news_today' %}">The Moringa Tribune</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'news:all_news' %}">All Articles <span class="sr-only">(current)</span></a>
        </li>
      </ul>

      <!-- The search form -->
      <form action="{% url 'news:search_results' %}" class="form-inline my-2 my-lg-0" method="GET" role="search">
        <input 
        class="form-control mr-sm-2 rounded-0" 
        type="search" 
        placeholder="Search Article" 
        aria-label="Search"
        name="article"
        >
        <button class="btn btn-outline-dark my-2 my-sm-0 rounded-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

news/templates/news/search.html
{% extends "news/layout.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      {% if articles %}
        <h2>Found {{ articles|length }} of searched term {{ message }} </h2>
      {% endif %}
    </div>
    <div class="row">
      {% if articles %}
        <ul>
          {% for article in articles %}
          <div class="card my-3">
            <a href="{% url 'news:article' article.id %}">
              <li class="card-title"><h1 class="card-title p-2 px-3 my-2">{{ article.title }}</h1></li>
            </a>
          </div>
        {% endfor %}
      {% else %}
        <h1>I am sorry, nothing came back from your search.</h1>
        </ul>
      {% endif %}
    </div>
  </div>
{% endblock content %}

news/templates/news/welcome.html
{% extends "news/layout.html" %}
{% block content %}
  {{block.super}}
{% endblock content %}